name: Cypress Tests

on:
  workflow_dispatch:
    imputs:
      cli:
        description: Run by cypress command line
        default: npx cypress run

jobs:
  cypres-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: install dependencies
        run: npm install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
