name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.0
        with:
          install-command: npm install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 9b09827b-8007-49a1-9529-7443e123ec66
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add More Groups (During Wait Time)
        run: |
          sleep 30 # Aguarda 30 segundos
          cypress run --tag <novo_nome_do_tag> --group <novo_nome_do_grupo> --ciBuildId 7483812733-20369650233

  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.0
        with:
          install-command: npm install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 9b09827b-8007-49a1-9529-7443e123ec66
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add More Groups (During Wait Time)
        run: |
          sleep 30 # Aguarda 30 segundos
          cypress run --tag <novo_nome_do_tag> --group <novo_nome_do_grupo> --ciBuildId 7483812733-20369650233

  cypress-e2e-firefox:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.0
        with:
          install-command: npm install
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 9b09827b-8007-49a1-9529-7443e123ec66
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add More Groups (During Wait Time)
        run: |
          sleep 30 # Aguarda 30 segundos
          cypress run --tag <novo_nome_do_tag> --group <novo_nome_do_grupo> --ciBuildId 7483812733-20369650233
